# Generated by Django 4.1.7 on 2023-04-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_crate_profile_create_profile_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilePhoto',
        ),
    ]
