# Generated by Django 4.1.7 on 2023-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_followers_profile_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=24)),
                ('count', models.IntegerField(blank=True, default=1)),
                ('edit', models.DateTimeField(auto_now_add=True, null=True)),
                ('create', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
